
version: '3.3'
services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    container_name: cuidapet
    restart: always
    environment:
      MYSQL_DATABASE: 'cuidapet_docker'   
      # MYSQL_USER: 'root'
      # MYSQL_PASSWORD: 'root'      
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    # expose:
    #   - '3306'
    volumes:
      - ../mysql_data:/var/lib/mysql
      # - './volumes/mysql:/var/lib/mysql'
      # - "./db.sql:/docker-entrypoint-initdb.d/1.sql"