name: api_cuidapet
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.2

dependencies:
  get_it: ^7.6.6
  args: ^2.4.2
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  dotenv: ^4.2.0
  mysql1: ^0.20.0
  logger: ^2.0.2+1
  injectable: ^2.3.2

dev_dependencies:
  # http: ^1.1.2
  shelf_router_generator: ^1.1.0
  lints: ^3.0.0
  test: ^1.25.1
  injectable_generator: ^2.4.1
  build_runner: ^2.4.8
